##
# docker-compose file for Viva con Agua Pool2 development
##

version: '3'

services:
  #########
  # Nginx #
  #########

  nginx-pool:
    image: nginx:1.13.7
    container_name: nginx-pool
    restart: unless-stopped
    volumes:
      - ./routes/nginx-pool/:/etc/nginx/conf.d/
    ports:
      - 80:80
    networks:
      pool-network:
        ipv4_address: 172.2.20.2
  
  #########      
  # Drops #
  #########

  arise:
    image: vivaconagua/arise:develop
    container_name: arise
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.50.1

  drops:
    image: vivaconagua/drops:develop
    container_name: drops
    restart: unless-stopped
    links: 
      - drops-database
    volumes:
      - ./volumes/drops/application.conf:/opt/docker/conf/application.conf
    networks:
      pool-network:
        ipv4_address: 172.2.100.1
  
  drops-database:
     image: mariadb:10.3
     container_name: drops-database
     environment: 
      - MYSQL_DATABASE=drops 
      - MYSQL_USER=drops
      - MYSQL_PASSWORD=drops 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
     volumes: 
       - ./volumes/drops-database/mysql/:/var/lib/mysql/
     networks:
       pool-network:
         ipv4_address: 172.2.200.1
  
  ##########
  # Stream #
  ##########

  stream-frontend:
    image: vivaconagua/stream-frontend:develop
    container_name: stream-frontend
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.50.2
  
  stream-backend:
    image: vivaconagua/stream-backend:develop
    container_name: stream-backend
    restart: unless-stopped
    links:
      - stream-database
    volumes:
      - ./volumes/stream-backend/application.conf:/opt/docker/conf/application.conf
    networks:
      pool-network:
        ipv4_address: 172.2.100.2

  stream-database:
     image: mariadb
     container_name: stream-database
     environment: 
      - MYSQL_DATABASE=stream 
      - MYSQL_USER=stream
      - MYSQL_PASSWORD=stream 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
     volumes: 
       - ./volumes/stream-database/mysql/:/var/lib/mysql/
     networks:
       pool-network:
         ipv4_address: 172.2.200.2

  #########
  # Waves #
  #########

  waves-frontend:
    image: vivaconagua/waves-frontend:develop
    container_name: waves-frontend
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.50.3
  
  waves-backend:
    image: vivaconagua/waves-backend:develop
    container_name: waves-backend
    restart: unless-stopped
    links:
     - waves-database
    environment:
      - HOST=172.2.200.3
      - USER_NAME=waves
      - PASSWORD=waves
      - DATABASE=waves 
      - OAUTH_BASE_URI=http://172.2.10.1
      - CLIENT_ID=wavesex
      - CLIENT_SECRET=waves
      - REDIRECT_URI=http://172.2.10.1/waves/api/v1/oauth
      - JWT_SECRET=“as0d9a08d0a9d8a0sd”
    networks:
      pool-network:
        ipv4_address: 172.2.100.3

  waves-database:
     image: mariadb
     #     build: ./waves-database
     command: --init-file /tmp/init.sql
     container_name: waves-database
     environment: 
      - MYSQL_DATABASE=waves 
      - MYSQL_USER=waves
      - MYSQL_PASSWORD=waves 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
     volumes: 
       - ./volumes/waves-database/init.sql:/tmp/init.sql
       - ./volumes/waves-database/mysql/:/var/lib/mysql/
     networks:
       pool-network:
         ipv4_address: 172.2.200.3

  #############
  # Dispsener #
  ############# 

  dispenser:
    image: vivaconagua/dispenser:develop
    container_name: dispenser
    restart: unless-stopped
    links:
      - dispenser-database
    volumes:
      - ./volumes/dispenser/application.conf:/opt/docker/conf/application.conf
      - ./navigation/:/opt/docker/conf/navigation/jsons/
    networks:
      pool-network:
        ipv4_address: 172.2.100.4

  dispenser-database:
    image: mongo
    container_name: dispenser-database
    restart: always
    volumes: 
       - ./volumes/dispenser-database/mongodb/:/data/db/
    networks:
      pool-network:
        ipv4_address: 172.2.200.4

  ################
  # Architecture #
  ################

  nats:
    image: nats:1.0.6
    container_name: pool-nats
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.150.1

################  
# pool-network #
################ 
networks:
  pool-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/16
