#!/bin/bash

##
# Pull docker and update
##
update_docker(){
  docker-compose pull $1 && docker-compose up -d $1
}

##
# Initialize navigation in dispenser
##
set_navigation(){
  echo "set Navigation";
  curl -X GET http://172.2.100.4:9000/dispenser/navigation/init;
}

##
# Print help
##
help(){
  echo "Usage: ./please <command> <serviceName / version>"
  echo "Commands: "
  echo " initNav                         # set navigation"
  echo " update                          # pull and update all services"
  echo " update <serviceName>            # pull and update given service"
}

case $1 in
  update) update_docker $2;;
  initNav) set_navigation;;
  *) help
esac
