#!/bin/bash


##
# reset up service 
##

reset_docker(){
  docker-compose rm -s -f $1 && docker-compose up -d $1
}

##
# Pull docker and update
##
update_docker(){
  docker-compose pull $1 && docker-compose up -d $1
}

restart_docker(){
  docker-compose restart $1
}
##
# Initialize navigation in dispenser
##
set_navigation(){
  echo "set Navigation";
  curl -X GET http://172.2.100.4:9000/dispenser/navigation/init;
}

##
# Create database dump
##

backup_database(){
  docker exec -i $1 sh -c 'exec mysqldump --all-databases -uroot -pyes' > ./dumps/${1}/${2}.sql &&
  echo "database backup successful"
}

##
# Restore database dump
##

restore_database(){
  docker exec -i $1 sh -c 'exec mysql -uroot -pyes' < ./dumps/${1}/${2}.sql &&
  echo "database successful restored"
}

##
# Restore database dump
##

punch(){
  echo ${1} 'just received a huge roundhouse kick from Chuck Norris. I hope it will remember this and will work correctly now!'
}
update_all(){
  git pull && docker-compose pull && docker-compose up -d

}

##
# Print help
##
help(){
  echo "Usage: ./please <command> <serviceName / version>"
  echo "Commands: "
  echo " initNav                              # set navigation"
  echo " restart                              # restart all services"
  echo " restart  <serviceName>               # restart service"
  echo " reset                                # reset all services"
  echo " reset    <serviceName>               # reset given service"
  echo " update                               # pull and update all services"
  echo " update   <serviceName>               # pull and update given service"
  echo " backup   <serviceName> <backupName>  # backup service database"
  echo " restore  <serviceName> <backupName>  # restore database backup"
  echo " punch                                # Lets punch a service when its not working correctly, just to reduce anger"
  echo " update-all                           # pull from git and update all docker"
  echo " help                                 # show this page"
}

case $1 in
  update) update_docker $2;;
  initNav) set_navigation;;
  restart) restart_docker $2;;
  reset) reset_docker $2;;
  backup) backup_database $2 $3;;
  restore) restore_database $2 $3;;
  punch) punch $2 ;;
  update-all) update_all;;
  *) help
esac
