-- MySQL Script generated by MySQL Workbench
-- Di 18 Feb 2020 18:02:16 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stream
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stream
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stream` DEFAULT CHARACTER SET latin1 ;
USE `stream` ;

-- -----------------------------------------------------
-- Table `stream`.`Deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Deposit` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NOT NULL,
  `full_amount` DOUBLE(10,2) NULL DEFAULT 0.00,
  `currency` VARCHAR(3) NULL DEFAULT 'EUR',
  `crew` VARCHAR(36) NOT NULL,
  `crew_name` VARCHAR(36) NOT NULL,
  `supporter` VARCHAR(36) NOT NULL,
  `supporter_name` VARCHAR(36) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `date_of_deposit` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `public_id_constraint` (`public_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`Taking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Taking` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NOT NULL,
  `received` BIGINT(20) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `comment` MEDIUMTEXT NULL DEFAULT NULL,
  `reason_for_payment` VARCHAR(255) NULL DEFAULT NULL,
  `receipt` TINYINT(1) NULL DEFAULT NULL,
  `author` VARCHAR(36) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `public_id_constraint` (`public_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`Deposit_Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Deposit_Unit` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NOT NULL,
  `amount` DOUBLE(10,2) NOT NULL,
  `currency` VARCHAR(3) NULL DEFAULT 'EUR',
  `created` BIGINT(20) NOT NULL,
  `deposit_id` BIGINT(20) NOT NULL,
  `taking_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `public_id_constraint` (`public_id` ASC),
  INDEX `FK_DEPOSIT` (`deposit_id` ASC),
  INDEX `FK_DONATION` (`taking_id` ASC),
  CONSTRAINT `FK_DEPOSIT`
    FOREIGN KEY (`deposit_id`)
    REFERENCES `stream`.`Deposit` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_DONATION`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`Taking` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`Household`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Household` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`Household_Version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Household_Version` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NULL DEFAULT NULL,
  `iban` VARCHAR(36) NULL DEFAULT NULL,
  `bic` VARCHAR(36) NULL DEFAULT NULL,
  `crew_id` VARCHAR(36) NOT NULL,
  `created` BIGINT(20) NULL DEFAULT NULL,
  `updated` BIGINT(20) NULL DEFAULT NULL,
  `author` VARCHAR(36) NULL DEFAULT NULL,
  `editor` VARCHAR(36) NULL DEFAULT NULL,
  `amount` DOUBLE NOT NULL,
  `currency` VARCHAR(5) NOT NULL DEFAULT 'EUR',
  `reason_what` VARCHAR(36) NULL DEFAULT NULL,
  `reason_wherefor` VARCHAR(36) NULL DEFAULT NULL,
  `request` TINYINT(1) NOT NULL,
  `volunteer_manager` VARCHAR(36) NULL DEFAULT NULL,
  `employee` VARCHAR(36) NULL DEFAULT NULL,
  `household_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_2_HOUSEHOLD` (`household_id` ASC),
  CONSTRAINT `FK_2_HOUSEHOLD`
    FOREIGN KEY (`household_id`)
    REFERENCES `stream`.`Household` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`Household_Version_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Household_Version_History` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NULL DEFAULT NULL,
  `iban` VARCHAR(36) NULL DEFAULT NULL,
  `bic` VARCHAR(36) NULL DEFAULT NULL,
  `crew_id` VARCHAR(36) NOT NULL,
  `created` BIGINT(20) NULL DEFAULT NULL,
  `updated` BIGINT(20) NULL DEFAULT NULL,
  `author` VARCHAR(36) NULL DEFAULT NULL,
  `editor` VARCHAR(36) NULL DEFAULT NULL,
  `amount` DOUBLE NOT NULL,
  `currency` VARCHAR(5) NOT NULL DEFAULT 'EUR',
  `reason_what` VARCHAR(36) NULL DEFAULT NULL,
  `reason_wherefor` VARCHAR(36) NULL DEFAULT NULL,
  `request` TINYINT(1) NOT NULL,
  `volunteer_manager` VARCHAR(36) NULL DEFAULT NULL,
  `employee` VARCHAR(36) NULL DEFAULT NULL,
  `household_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_3_HOUSEHOLD` (`household_id` ASC),
  CONSTRAINT `FK_3_HOUSEHOLD`
    FOREIGN KEY (`household_id`)
    REFERENCES `stream`.`Household` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`InvolvedCrew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`InvolvedCrew` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `taking_id` BIGINT(20) NOT NULL,
  `crew_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Crew_Taking` (`taking_id` ASC),
  CONSTRAINT `FK_Crew_Taking`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`Taking` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`InvolvedSupporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`InvolvedSupporter` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `taking_id` BIGINT(20) NULL DEFAULT NULL,
  `supporter_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Sup_Donation` (`taking_id` ASC),
  CONSTRAINT `FK_Sup_Donation`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`Taking` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`Place_Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Place_Message` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(36) NOT NULL,
  `token` VARCHAR(36) NOT NULL,
  `household_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_1_HOUSEHOLD` (`household_id` ASC),
  CONSTRAINT `FK_1_HOUSEHOLD`
    FOREIGN KEY (`household_id`)
    REFERENCES `stream`.`Household` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`Source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Source` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(36) NOT NULL,
  `taking_id` BIGINT(20) NULL DEFAULT NULL,
  `category` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `amount` DOUBLE NOT NULL,
  `currency` VARCHAR(5) NOT NULL DEFAULT 'EUR',
  `type_of_source` VARCHAR(255) NOT NULL,
  `type_location` VARCHAR(36) NULL DEFAULT NULL,
  `type_contact_person` VARCHAR(36) NULL DEFAULT NULL,
  `type_email` VARCHAR(36) NULL DEFAULT NULL,
  `type_address` VARCHAR(36) NULL DEFAULT NULL,
  `receipt` TINYINT(1) NULL DEFAULT NULL,
  `norms` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Sou_Donation` (`taking_id` ASC),
  CONSTRAINT `FK_Sou_Donation`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`Taking` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `stream`.`Confirmed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Confirmed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_uuid` VARCHAR(36) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `date_of_confirm` BIGINT(20) NOT NULL,
  `Deposit_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Confirmed_Deposit1_idx` (`Deposit_id` ASC),
  CONSTRAINT `fk_Confirmed_Deposit1`
    FOREIGN KEY (`Deposit_id`)
    REFERENCES `stream`.`Deposit` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
